// utilis/currencies.ts

export const CURRENCY_NAMES: Record<string, string> = {
    USD: "US Dollar",
    EUR: "Euro",
    GBP: "British Pound",
    AUD: "Australian Dollar",
    CAD: "Canadian Dollar",
    JPY: "Japanese Yen",
    INR: "Indian Rupee",
    BRL: "Brazilian Real",
    CNY: "Chinese Yuan",
    CHF: "Swiss Franc",
    NPR: "Nepalese Rupee",
    NZD: "New Zealand Dollar",
    SGD: "Singapore Dollar",
    SEK: "Swedish Krona",
    ZAR: "South African Rand",
    AED: "United Arab Emirates Dirham",
    MYR: "Malaysian Ringgit",
    TRY: "Turkish Lira",
    // Additional Popular & Regional Currencies
  SAR: "Saudi Riyal",
  QAR: "Qatari Rial",
  KWD: "Kuwaiti Dinar",
  BHD: "Bahraini Dinar",
  OMR: "Omani Rial",
  THB: "Thai Baht",
  KRW: "South Korean Won",
  HKD: "Hong Kong Dollar",
  NOK: "Norwegian Krone",
  DKK: "Danish Krone",
  PLN: "Polish Zloty",
  MXN: "Mexican Peso",
  IDR: "Indonesian Rupiah",
  PHP: "Philippine Peso",
  PKR: "Pakistani Rupee",
  BDT: "Bangladeshi Taka",
  LKR: "Sri Lankan Rupee",
  VND: "Vietnamese Dong",
  EGP: "Egyptian Pound",
  ILS: "Israeli New Shekel",
  CZK: "Czech Koruna",
  HUF: "Hungarian Forint",
  RON: "Romanian Leu",
  CLP: "Chilean Peso",
  COP: "Colombian Peso",
  PEN: "Peruvian Sol",
  ARS: "Argentine Peso",
  NGN: "Nigerian Naira",
  KES: "Kenyan Shilling",
  GHS: "Ghanaian Cedi",
  MAD: "Moroccan Dirham",
  TWD: "New Taiwan Dollar",
  MVR: "Maldivian Rufiyaa",
  BND: "Brunei Dollar",
  IQD: "Iraqi Dinar",
  JOD: "Jordanian Dinar",
  DZD: "Algerian Dinar",
  UAH: "Ukrainian Hryvnia",
  RUB: "Russian Ruble",
  
};

// A helper function to safely get a name, falling back to the code if not found
export function getCurrencyName(code: string): string {
    return CURRENCY_NAMES[code] || code;
}
